keywords = [
    "LLC", "LLP", "LLLP", "LP", "LTD", "CORP", "CO", "PLC", "GMBH", "AG", "SA", "BV", "SRL", "SARL", "PTY",
    "ACC", "ACCT", "ACCTS", "INST", "INSTN", "INSTNS", "INSTL", "GRP", "GRPS", "INC.", "LTD.", "CO.", "CORP.",
    "LLP", "PLLC", "PC", "ASSN", "NATL", "INTL", "GR", "TRU", "TR", "TRUS", "TRS", "ADV",
    "GROUP", "PARTNERS", "ASSOCIATES", "HOLDINGS", "ENTERPRISES", "INDUSTRIES", "SYSTEMS", "SOLUTIONS",
    "INTERNATIONAL", "GLOBAL", "TECHNOLOGIES", "TRUST", "TRUSTEE", "TRUSTEES", "AGENCY", "MANAGEMENT",
    "STUDIO", "WORKS", "PRODUCTIONS", "CORPORATION", "BANK", "INSURANCE", "LOGISTICS", "CONSTRUCTION",
    "REALTY", "PHARMACEUTICALS", "CONSULTING", "NATIONAL", "UNIVERSAL", "WORLD", "INCORPORATED", "LIMITED",
    "PARTNERSHIP", "PROPERTIES", "PROPERTY", "UNIVERSITY", "COLLEGE", "ACADEMY", "INSTITUTE", "INSTITUTION",
    "CENTER", "CENTRE", "CLINIC", "MEDICAL", "HEALTH", "HEALTHCARE", "HOSPITAL", "SCHOOL", "ACADEMY",
    "CHARITY", "CHARITABLE", "FOUNDATION", "ASSOCIATION", "CLUB", "SOCIETY", "COOPERATIVE", "CO-OP",
    "MORTGAGE", "MGMT", "CHICAGO", "INVESTMENTS", "INVESTMENT", "INVEST", "INVESTORS", "ASSOC", "ASSNS",
    "ASSOCN", "ASSOCNS", "ASSOCIA", "COMPANY", "COMPANIES", "ACCOUNT", "SHOPPING", "SERVICES", "UNION",
    "NETWORK", "TRUST", "VENTURES", "EQUITY", "EQUITIES", "CAPITAL", "COMMUNITY", "INITIATIVE", "INITIATIVES",
    "DEVELOPMENT", "DEVELOPMENTS", "DEVELOPER", "DEVELOPERS", "FOODS", "CHEVROLE", "REAL ESTATE", "ESTATE",
    "LEGAL", "ILLINOIS", "ADVOCACY", "ADVOCATES", "ADVOCAT", "CTLTC"
]
