geo_dict = {
    "ALBANY PARK": "Chicago",
    "ARCHER HEIGHTS": "Chicago",
    "ARMOUR SQUARE": "Chicago",
    "ASHBURN": "Chicago",
    "AUBURN GRESHAM": "Chicago",
    "AUSTIN": "Chicago",
    "AVALON PARK": "Chicago",
    "AVONDALE": "Chicago",
    "BELMONT CRAGIN": "Chicago",
    "BEVERLY": "Chicago",
    "BRIDGEPORT": "Chicago",
    "BRIGHTON PARK": "Chicago",
    "BURNSIDE": "Chicago",
    "CALUMET HEIGHTS": "Chicago",
    "CHATHAM": "Chicago",
    "CHICAGO LAWN": "Chicago",
    "CLEARING": "Chicago",
    "DOUGLAS": "Chicago",
    "DUNNING": "Chicago",
    "EAST GARFIELD PARK": "Chicago",
    "EAST SIDE": "Chicago",
    "EDGEWATER": "Chicago",
    "EDISON PARK": "Chicago",
    "ENGLEWOOD": "Chicago",
    "FOREST GLEN": "Chicago",
    "FULLER PARK": "Chicago",
    "GAGE PARK": "Chicago",
    "GARFIELD RIDGE": "Chicago",
    "GRAND BOULEVARD": "Chicago",
    "GREATER GRAND CROSSING": "Chicago",
    "HEGEWISCH": "Chicago",
    "HERMOSA": "Chicago",
    "HUMBOLDT PARK": "Chicago",
    "HYDE PARK": "Chicago",
    "IRVING PARK": "Chicago",
    "JEFFERSON PARK": "Chicago",
    "KENWOOD": "Chicago",
    "LAKE VIEW": "Chicago",
    "LINCOLN PARK": "Chicago",
    "LINCOLN SQUARE": "Chicago",
    "LOGAN SQUARE": "Chicago",
    "LOOP": "Chicago",
    "LOWER WEST SIDE": "Chicago",
    "MCKINLEY PARK": "Chicago",
    "MONTCLARE": "Chicago",
    "MORGAN PARK": "Chicago",
    "MOUNT GREENWOOD": "Chicago",
    "NEAR NORTH SIDE": "Chicago",
    "NEAR SOUTH SIDE": "Chicago",
    "NEAR WEST SIDE": "Chicago",
    "NEW CITY": "Chicago",
    "NORTH CENTER": "Chicago",
    "NORTH LAWNDALE": "Chicago",
    "NORTH PARK": "Chicago",
    "NORWOOD PARK": "Chicago",
    "OAKLAND": "Chicago",
    "PORTAGE PARK": "Chicago",
    "PULLMAN": "Chicago",
    "RIVERDALE": "Chicago",
    "ROGERS PARK": "Chicago",
    "ROSELAND": "Chicago",
    "SOUTH CHICAGO": "Chicago",
    "SOUTH DEERING": "Chicago",
    "SOUTH LAWNDALE": "Chicago",
    "SOUTH SHORE": "Chicago",
    "UPTOWN": "Chicago",
    "WASHINGTON HEIGHTS": "Chicago",
    "WASHINGTON PARK": "Chicago",
    "WEST ELSDON": "Chicago",
    "WEST ENGLEWOOD": "Chicago",
    "WEST GARFIELD PARK": "Chicago",
    "WEST LAWN": "Chicago",
    "WEST PULLMAN": "Chicago",
    "WEST RIDGE": "Chicago",
    "WEST TOWN": "Chicago",
    "WOODLAWN": "Chicago",
    "OHARE": "Chicago",
    "BLOOM TWP": "Suburban Cook",
    "BREMEN TWP": "Suburban Cook",
    "CITY OF BERWYN": "Suburban Cook",
    "CITY OF BLUE ISLAND": "Suburban Cook",
    "CITY OF BURBANK": "Suburban Cook",
    "CITY OF CALUMET CITY": "Suburban Cook",
    "CITY OF CHICAGO HEIGHTS": "Suburban Cook",
    "CITY OF CICERO": "Suburban Cook",
    "CITY OF COUNTRY CLUB HILLS": "Suburban Cook",
    "CITY OF COUNTRYSIDE": "Suburban Cook",
    "CITY OF DES PLAINES": "Suburban Cook",
    "CITY OF ELGIN": "Suburban Cook",
    "CITY OF EVANSTON": "Suburban Cook",
    "CITY OF HARVEY": "Suburban Cook",
    "CITY OF HICKORY HILLS": "Suburban Cook",
    "CITY OF HOMETOWN": "Suburban Cook",
    "CITY OF MARKHAM": "Suburban Cook",
    "CITY OF NORTH LAKE": "Suburban Cook",
    "CITY OF OAK FOREST": "Suburban Cook",
    "CITY OF PALOS HEIGHTS": "Suburban Cook",
    "CITY OF PALOS HILLS": "Suburban Cook",
    "CITY OF PARK RIDGE": "Suburban Cook",
    "CITY OF PROSPECT HEIGHTS": "Suburban Cook",
    "CITY OF ROLLING MEADOWS": "Suburban Cook",
    "HANOVER TWP": "Suburban Cook",
    "LEMONT TWP": "Suburban Cook",
    "LEYDEN TWP": "Suburban Cook",
    "LYONS TWP": "Suburban Cook",
    "MAINE TWP": "Suburban Cook",
    "NORTHFIELD TWP": "Suburban Cook",
    "ORLAND TWP": "Suburban Cook",
    "PALATINE TWP": "Suburban Cook",
    "PALOS TWP": "Suburban Cook",
    "RICH TWP": "Suburban Cook",
    "SCHAUMBURG TWP": "Suburban Cook",
    "STICKNEY TWP": "Suburban Cook",
    "THORNTON TWP": "Suburban Cook",
    "BARRINGTON TWP": "Suburban Cook",
    "ELK GROVE TWP": "Suburban Cook",
    'NEW TRIER TWP': "Suburban Cook",
    "NORWOOD PARK TWP":"Suburban Cook",
    "PROVISO TWP":"Suburban Cook",
    "RIVERSIDE TWP": "Suburban Cook",
    "VILLAGE OF DEER PARK": "Suburban Cook",
    "VILLAGE OF GOLF": "Suburban Cook",
    "VILLAGE OF MC COOK":"Suburban Cook",
    "VILLAGE OF OAK BROOK": "Suburban Cook",
    "VILLAGE OF UNIVERSITY PARK": "Suburban Cook",
    "VILLAGE OF ALSIP": "Suburban Cook",
    "VILLAGE OF ARLINGTON HEIGHTS": "Suburban Cook",
    "VILLAGE OF BARRINGTON": "Suburban Cook",
    "VILLAGE OF BARRINGTON HILLS": "Suburban Cook",
    "VILLAGE OF BARTLETT": "Suburban Cook",
    "VILLAGE OF BEDFORD PARK": "Suburban Cook",
    "VILLAGE OF BELLWOOD": "Suburban Cook",
    "VILLAGE OF BERKELEY": "Suburban Cook",
    "VILLAGE OF BRIDGEVIEW": "Suburban Cook",
    "VILLAGE OF BROADVIEW": "Suburban Cook",
    "VILLAGE OF BROOKFIELD": "Suburban Cook",
    "VILLAGE OF BUFFALO GROVE": "Suburban Cook",
    "VILLAGE OF BURNHAM": "Suburban Cook",
    "VILLAGE OF BURR RIDGE": "Suburban Cook",
    "VILLAGE OF CALUMET PARK": "Suburban Cook",
    "VILLAGE OF CHICAGO RIDGE": "Suburban Cook",
    "VILLAGE OF CRESTWOOD": "Suburban Cook",
    "VILLAGE OF DIXMOOR": "Suburban Cook",
    "VILLAGE OF DOLTON": "Suburban Cook",
    "VILLAGE OF EAST HAZELCREST": "Suburban Cook",
    "VILLAGE OF ELK GROVE VILLAGE": "Suburban Cook",
    "VILLAGE OF ELMWOOD PARK": "Suburban Cook",
    "VILLAGE OF EVERGREEN PARK": "Suburban Cook",
    "VILLAGE OF FLOSSMOOR": "Suburban Cook",
    "VILLAGE OF FORD HEIGHTS": "Suburban Cook",
    "VILLAGE OF FOREST PARK": "Suburban Cook",
    "VILLAGE OF FORESTVIEW": "Suburban Cook",
    "VILLAGE OF FRANKLIN PARK": "Suburban Cook",
    "VILLAGE OF GLENCOE": "Suburban Cook",
    "VILLAGE OF GLENVIEW": "Suburban Cook",
    "VILLAGE OF GLENWOOD": "Suburban Cook",
    "VILLAGE OF HANOVER PARK": "Suburban Cook",
    "VILLAGE OF HARWOOD HEIGHTS": "Suburban Cook",
    "VILLAGE OF HAZELCREST": "Suburban Cook",
    "VILLAGE OF HILLSIDE": "Suburban Cook",
    "VILLAGE OF HINSDALE": "Suburban Cook",
    "VILLAGE OF HODGKINS": "Suburban Cook",
    "VILLAGE OF HOFFMAN ESTATES": "Suburban Cook",
    "VILLAGE OF HOMEWOOD": "Suburban Cook",
    "VILLAGE OF INDIAN HEAD PARK": "Suburban Cook",
    "VILLAGE OF INVERNESS": "Suburban Cook",
    "VILLAGE OF JUSTICE": "Suburban Cook",
    "VILLAGE OF KENILWORTH": "Suburban Cook",
    "VILLAGE OF LA GRANGE": "Suburban Cook",
    "VILLAGE OF LA GRANGE PARK": "Suburban Cook",
    "VILLAGE OF LANSING": "Suburban Cook",
    "VILLAGE OF LEMONT": "Suburban Cook",
    "VILLAGE OF LINCOLNWOOD": "Suburban Cook",
    "VILLAGE OF LYNWOOD": "Suburban Cook",
    "VILLAGE OF LYONS": "Suburban Cook",
    "VILLAGE OF MATTESON": "Suburban Cook",
    "VILLAGE OF MAYWOOD": "Suburban Cook",
    "VILLAGE OF MELROSE PARK": "Suburban Cook",
    "VILLAGE OF MERRIONETTE PARK": "Suburban Cook",
    "VILLAGE OF MIDLOTHIAN": "Suburban Cook",
    "VILLAGE OF MORTON GROVE": "Suburban Cook",
    "VILLAGE OF MT PROSPECT": "Suburban Cook",
    "VILLAGE OF NILES": "Suburban Cook",
    "VILLAGE OF NORRIDGE": "Suburban Cook",
    "VILLAGE OF NORTH RIVERSIDE": "Suburban Cook",
    "VILLAGE OF NORTHBROOK": "Suburban Cook",
    "VILLAGE OF NORTHFIELD": "Suburban Cook",
    "VILLAGE OF OAK LAWN": "Suburban Cook",
    "VILLAGE OF OAK PARK": "Suburban Cook",
    "VILLAGE OF OLYMPIA FIELDS": "Suburban Cook",
    "VILLAGE OF ORLAND HILLS": "Suburban Cook",
    "VILLAGE OF ORLAND PARK": "Suburban Cook",
    "VILLAGE OF PALATINE": "Suburban Cook",
    "VILLAGE OF PALOS PARK": "Suburban Cook",
    "VILLAGE OF PARK FOREST": "Suburban Cook",
    "VILLAGE OF PHOENIX": "Suburban Cook",
    "VILLAGE OF POSEN": "Suburban Cook",
    "VILLAGE OF RICHTON PARK": "Suburban Cook",
    "VILLAGE OF RIVER FOREST": "Suburban Cook",
    "VILLAGE OF RIVER GROVE": "Suburban Cook",
    "VILLAGE OF RIVERDALE": "Suburban Cook",
    "VILLAGE OF RIVERSIDE": "Suburban Cook",
    "VILLAGE OF ROBBINS": "Suburban Cook",
    "VILLAGE OF ROSELLE": "Suburban Cook",
    "VILLAGE OF ROSEMONT": "Suburban Cook",
    "VILLAGE OF SAUK VILLAGE": "Suburban Cook",
    "VILLAGE OF SCHAUMBURG": "Suburban Cook",
    "VILLAGE OF SCHILLER PARK": "Suburban Cook",
    "VILLAGE OF SKOKIE": "Suburban Cook",
    "VILLAGE OF SOUTH BARRINGTON": "Suburban Cook",
    "VILLAGE OF SOUTH CHICAGO HEIGHTS": "Suburban Cook",
    "VILLAGE OF SOUTH HOLLAND": "Suburban Cook",
    "VILLAGE OF STEGER": "Suburban Cook",
    "VILLAGE OF STICKNEY": "Suburban Cook",
    "VILLAGE OF STONE PARK": "Suburban Cook",
    "VILLAGE OF STREAMWOOD": "Suburban Cook",
    "VILLAGE OF SUMMIT": "Suburban Cook",
    "VILLAGE OF THORNTON": "Suburban Cook",
    "VILLAGE OF TINLEY PARK": "Suburban Cook",
    "VILLAGE OF WESTCHESTER": "Suburban Cook",
    "VILLAGE OF WESTERN SPRINGS": "Suburban Cook",
    "VILLAGE OF WHEELING": "Suburban Cook",
    "VILLAGE OF WILLOW SPRINGS": "Suburban Cook",
    "VILLAGE OF WILMETTE": "Suburban Cook",
    "VILLAGE OF WINNETKA": "Suburban Cook",
    "VILLAGE OF WORTH": "Suburban Cook",
    "WHEELING TWP": "Suburban Cook",
    "WORTH TWP": "Suburban Cook",
    "VILLAGE OF BENSENVILLE": "Suburban Cook",
    "VILLAGE OF FRANKFORT": "Suburban Cook",
    "VILLAGE OF DEERFIELD": "Suburban Cook",
    "VILLAGE OF HOMER GLEN": "Suburban Cook"
}
